name: NodeJS with Webpack

on:
  push:
    branches:
      - main
      - dev
  pull_request:
    types: [opened, reopened]

permissions: write-all

jobs:
  build:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [20.x]
    
    steps:
    - uses: actions/checkout@v3

    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v3
      with:
        node-version: ${{ matrix.node-version }}

    - name: Get version
      id: get_version
      shell: bash
      run: |
        VERSION=$(jq -r .version package.json)
        echo "VERSION=$VERSION" >> $GITHUB_ENV
        echo ${{ env.VERSION }}

    - name: Build
      run: |
        npm install
        npm run build --env 'version= ${{ steps.extract_branch.outputs.branch }}'

    - name: Pack
      run: |
        zip -r particle.js_${{ steps.extract_branch.outputs.branch }}.zip dist

    - uses: actions/upload-artifact@v3
      with:
        name: build
        path: particle.js_${{ steps.extract_branch.outputs.branch }}.zip

  deploy:
    if: github.ref == 'refs/heads/main'
    needs: build
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3

    - name: Get version
      id: get_version
      shell: bash
      run: |
        VERSION=$(jq -r .version package.json)
        echo "VERSION=$VERSION" >> $GITHUB_ENV
        echo ${{ env.VERSION }}

    - uses: actions/download-artifact@v3
      with:
        name: build

    - name: Extract
      run: |
        unzip -o particle.js_${{ steps.extract_branch.outputs.branch }}.zip

    - uses: ncipollo/release-action@v1
      with:
        artifacts: "particle.js*.zip"
        token: ${{ secrets.GITHUB_TOKEN }}
        tag: ${{ env.VERSION }}

    - name: Deploy gh-pages
      uses: JamesIves/github-pages-deploy-action@v4
      with:
        folder: dist
        branch: gh-pages
