name: NodeJS with Webpack

on:
  push:
    branches:
      - main
      - dev
      - release
    tags:
      - v*

permissions:
  contents: write
  pull-requests: write

jobs:
  build:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [16.x]
    
    steps:
    - uses: actions/checkout@v3

    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v3
      with:
        node-version: ${{ matrix.node-version }}

    - name: Build
      run: |
        npm install
        npm run build --env "version=${GITHUB_REF#refs/*/}"

    - name: Pack
      run: |
        zip -r particle.js_${GITHUB_REF#refs/*/}.zip dist

    - uses: ncipollo/release-action@v1
      if: startsWith(github.ref, 'refs/tags/v')
      with:
        artifacts: "particle.js*.zip"
        token: ${{ secrets.GITHUB_TOKEN }}
        draft: true
        
    - name: Create Pull Request
      if: startsWith(github.ref, 'refs/heads/release')
      uses: peter-evans/create-pull-request@v4

