name: NodeJS with Webpack

on:
  push:
    tags: "v*"

jobs:
  build:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [16.x]
    
    steps:
    - uses: actions/checkout@v3

    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v3
      with:
        node-version: ${{ matrix.node-version }}

    - name: Build
      run: |
        npm install
        npx webpack

    - name: Pack
      run: |
        zip -r particle.js_${GITHUB_REF#refs/*/}.zip dist

    - uses: ncipollo/release-action@v1
      with:
        artifacts: "particle.js.zip"
        token: ${{ secrets.GITHUB_TOKEN }}
        draft: true