name: NodeJS with Webpack

on:
  push:
    branches:
      - main
      - dev
    tags:
      - v*
  pull_request:
    types: [opened, reopened]

permissions:
  contents: write
  pull-requests: write

jobs:
  build:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [16.x]
    
    steps:
    - uses: actions/checkout@v3

    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v3
      with:
        node-version: ${{ matrix.node-version }}

    - name: Build
      run: |
        npm install
        npm run build --env "version=${GITHUB_REF#refs/*/}"

    - name: Pack
      if: startsWith(github.ref, 'refs/tags/v')
      run: |
        zip -r particle.js_${GITHUB_REF#refs/*/}.zip dist

    - uses: ncipollo/release-action@v1
      if: startsWith(github.ref, 'refs/tags/v')
      with:
        artifacts: "particle.js*.zip"
        token: ${{ secrets.GITHUB_TOKEN }}
        draft: true

    - name: Deploy gh-pages
      if: startsWith(github.ref, 'refs/tags/v')
      uses: JamesIves/github-pages-deploy-action@v4
      with:
        folder: dist
        branch: gh-pages

    - name: Create Pull Request
      if: startsWith(github.ref, 'refs/tags/v')
      uses: actions/github-script@v6
      with:
        script: |
          const { repo, owner } = context.repo;
          const result = await github.rest.pulls.create({
            head: '${{ github.ref_name }}',
            owner,
            repo,
            base: 'main',
            body: [
              'Automated PR for RC ${{ github.ref_name }}'
            ].join('\n'),
          });
