name: NodeJS with Webpack

on:
  push:
    branches:
      - main
      - dev
      - react

permissions: write-all

jobs:
  build:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [20.x]
    
    steps:
    - uses: actions/checkout@v3

    - name: Setup Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v3
      with:
        node-version: ${{ matrix.node-version }}

    - name: Get version
      id: get_version
      shell: bash
      run: |
        BUILD_VERSION=$(jq -r .version package.json)
        echo "BUILD_VERSION=v$BUILD_VERSION" >> $GITHUB_ENV

    - name: Build
      run: |
        npm install
        npm run prod --env version=${{ env.BUILD_VERSION }} --env gtag_config=$GTAG_CONFIG
      env:
        GTAG_CONFIG: ${{ vars.GTAG_CONFIG }}

    - name: Pack
      run: |
        zip -r particle.js_${{ env.BUILD_VERSION }}.zip dist

    - uses: actions/upload-artifact@v3
      with:
        name: build
        path: particle.js_${{ env.BUILD_VERSION }}.zip

  deploy:
    if: github.ref == 'refs/heads/main'
    needs: build
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3

    - name: Get version
      id: get_version
      shell: bash
      run: |
        BUILD_VERSION=$(jq -r .version package.json)
        echo "BUILD_VERSION=v$BUILD_VERSION" >> $GITHUB_ENV

    - uses: actions/download-artifact@v3
      with:
        name: build

    - name: Extract
      run: |
        unzip -o particle.js_${{ env.BUILD_VERSION }}.zip

    - uses: ncipollo/release-action@v1
      with:
        artifacts: "particle.js*.zip"
        token: ${{ secrets.GITHUB_TOKEN }}
        tag: ${{ env.BUILD_VERSION }}
        draft: true
        commit: ${{ github.ref }}

    - name: Deploy gh-pages
      uses: JamesIves/github-pages-deploy-action@v4
      with:
        folder: dist
        branch: gh-pages
