name: NodeJS with Webpack

on:
  push:
    branches:
      - main
      - dev
      - release*
    tags:
      - v*
  pull_request:
    types: [opened, reopened]

permissions: write-all

jobs:
  build:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [16.x]
    
    steps:
    - uses: actions/checkout@v3

    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v3
      with:
        node-version: ${{ matrix.node-version }}

    - name: Extract branch name
      shell: bash
      run: echo "##[set-output name=branch;]$(echo ${GITHUB_REF#refs/heads/release_})"
      id: extract_branch

    - name: Build
      run: |
        npm install
        npm run build --env 'version= ${{ steps.extract_branch.outputs.branch }}'

    - name: Pack
      run: |
        zip -r particle.js_${{ steps.extract_branch.outputs.branch }}.zip dist

    # - uses: actions/upload-artifact@v3
    #   with:
    #     name: build
    #     path: particle.js_${{ steps.extract_branch.outputs.branch }}.zip

  deploy:
    if: startsWith(github.ref, 'refs/heads/release')
    needs: build
    runs-on: ubuntu-latest

    steps:
    # - uses: actions/checkout@v3

    # - name: Extract branch name
    #   shell: bash
    #   run: echo "##[set-output name=branch;]$(echo ${GITHUB_REF#refs/heads/release_})"
    #   id: extract_branch

    # - uses: actions/download-artifact@v3
    #   with:
    #     name: build

    # - name: Extract
    #   run: |
    #     unzip particle.js_${{ steps.extract_branch.outputs.branch }}.zip

    - name: Create Pull Request
      uses: actions/github-script@v6
      with:
        script: |
          const { repo, owner } = context.repo;

          let branch = '${{ github.ref_name }}';
          branch = branch.replace(/^.*[\\\/]/, '')

          let result = await github.rest.pulls.create({
            head: '${{ github.ref_name }}',
            owner,
            repo,
            base: 'main',
            title: 'Merge ' + branch,
            body: [
              'Automated PR for RC ' + branch
            ].join('\n')
          });
          console.log(result);

    - uses: ncipollo/release-action@v1
      with:
        artifacts: "particle.js*.zip"
        token: ${{ secrets.GITHUB_TOKEN }}
        tag: ${{ steps.extract_branch.outputs.branch }}

    - name: Deploy gh-pages
      uses: JamesIves/github-pages-deploy-action@v4
      with:
        folder: dist
        branch: gh-pages
